#!/bin/sh

function INFO()
{
	echo -e "[*] $1"
}

function FAILURE()
{
	echo -e "\e[1;31m[*]\e[0m $1"
}

function SUCCESS()
{
	echo -e "\e[1;32m[*]\e[0m $1"
}

function WARNING()
{
	echo -e "\e[1;33m[*]\e[0m $1"
}
